# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  networking.hostName = "eltnix";

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/dcc5294a-7fba-4e30-995d-86c1816b6272";
      fsType = "btrfs";
      options = [ "subvol=root,relatime,compress=zstd" ];
    };
  boot.initrd.luks.devices = {
    enc = {
      device = "/dev/disk/by-uuid/3e4f3d4e-21bb-447f-8010-fe0b1670071d";
      preLVM = true;
      allowDiscards = true;
    };
  };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/dcc5294a-7fba-4e30-995d-86c1816b6272";
      fsType = "btrfs";
      options = [ "subvol=home,relatime,compress=zstd" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/dcc5294a-7fba-4e30-995d-86c1816b6272";
      fsType = "btrfs";
      options = [ "subvol=nix,noatime,compress=zstd" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8080-4862";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };
  fileSystems."/storage" =
    { device = "/dev/disk/by-uuid/229b8e0e-52c5-4199-9150-882de9719253";
      fsType = "ext4";
      options = [ "noatime" ];
    };
  swapDevices =
    [ { device = "/dev/disk/by-uuid/bd8bdb55-f0f9-4e24-9996-482d2eff1337"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
