# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  networking.hostName = "x150nix";
  networking.firewall.allowedTCPPorts = [ 2234 ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices = {
    enc = {
      device = "/dev/disk/by-uuid/4fcdd65f-cf97-4f2a-b45e-822f92702e94";
      preLVM = true;
      allowDiscards = true;
    };
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/84d15bff-ec0d-4a8c-af68-d630caaee57e";
      fsType = "btrfs";
      options = [ "subvol=root,relatime,compress=zstd" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/84d15bff-ec0d-4a8c-af68-d630caaee57e";
      fsType = "btrfs";
      options = [ "subvol=nix,noatime,compress=zstd" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/84d15bff-ec0d-4a8c-af68-d630caaee57e";
      fsType = "btrfs";
      options = [ "subvol=home,relatime,compress=zstd" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F4F5-1010";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/storage" =
    { device = "/dev/disk/by-uuid/c1e5cbac-d768-4ba7-9ec7-618236bc287a";
      fsType = "btrfs";
      options = [ "nofail" "relatime" ];
    };

  fileSystems."/g1" =
    { device = "/dev/disk/by-uuid/ace4243a-fed9-4ae3-a63d-cf831481177d";
      fsType = "ext4";
      options = [ "nofail" "relatime" ];
    };

  fileSystems."/g2" =
    { device = "/dev/disk/by-uuid/ceb500b0-9f48-4ab0-818d-63f3154d95ec";
      fsType = "ext4";
      options = [ "nofail" "relatime" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/91bf0e0e-ca50-4133-996a-ab240e64efab"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  #  networking.useDHCP = lib.mkDefault true;
   networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.tailscale0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
